### ISSUE TITLE
Add red bar for closed activities

### ISSUE THREAD

**Issue by theRoughCode** [uwblueprint/water-festival#132]
For activities that are closed, we want to display a red bar at the top in the Activity Details screen.  

Check out the [designs](https://drive.google.com/file/d/1jZm2XXn-afLtdzQhFoC-ykzuFjw_bySb/view?usp=sharing)

**Comment by amyqiu** [comment]
What would we put as the error message for these?

**Comment by theRoughCode** [comment]
that would be the `state` field in the Schema.  If there is none, we need to come up with a default message.  What do you think that should be?

**Comment by amyqiu** [comment]
Maybe something along the lines of "This event is currently closed due to unforeseen circumstances, thanks for your understanding"?

**Comment by theRoughCode** [comment]
Yea, let's bring it up in Slack!
