### ISSUE TITLE
As a user, when I click on an event from the list, I want to see the event expand to show the event details

### ISSUE THREAD

**Issue by Steven-Jia** [uwblueprint/water-festival#15]
Design: https://drive.google.com/drive/u/2/folders/0B9tUHkbrCEPMMmFha0hmRFZiZGs

The following info should be included
- [ ] Name
- [ ] Location (i.e. station number)
- [ ] Description
- [ ] Grade Levels
- [ ] Image (if it exists)
- [ ] Scheduled Times (if it exists)
- [ ] Category
- [ ] Tags

Focus on layout for now. Add default values to be displayed if the values are null.

More requirements:
- Back button
- "Add to my events" button

**Comment by theRoughCode** [comment]
Done in #42
