### ISSUE TITLE
As a developer, I want to be able to POST a festival event to the server with the following fields

### ISSUE THREAD

**Issue by theRoughCode** [uwblueprint/water-festival#38]
The main table named "events" should have these fields:
- [ ] title: String,
- [ ] description: String,
- [ ] startTime: Date,
- [ ] endTime: Date,
- [ ] location: String,
- [ ] grade: Number,
- [ ] imageURI: String

**Comment by theRoughCode** [comment]
Look into: https://github.com/uwblueprint/water-festival/pull/34/files

**Comment by amyqiu** [comment]
Should I merge in the events.js file created in that pull request (#34)? Or create a new one?

**Comment by theRoughCode** [comment]
@amyqiu Create a new one.  That's just for reference, do not merge it in

**Comment by amyqiu** [comment]
Okay got it
