### ISSUE TITLE
Missing `goBack` function props

### ISSUE THREAD

**Issue by theRoughCode** [uwblueprint/water-festival#55]
`Header.js` requries a `goBack` and `hasBackButton` props, but `FaqScreen,js` is not passing it down.

**Comment by pratyushpal** [comment]
FaqScreen.js doesn't use goBack and hasBackButton props so we'll be expecting an 'unused prop' error in this case. 
I can remove the isRequired from the goBack and hasBackButton. Since these are inbuilt, the type check is pretty much confirmed for those. What do you think?
