### ISSUE TITLE
As a user, I want to see the festival map

### ISSUE THREAD

**Issue by Steven-Jia** [uwblueprint/water-festival#6]
Design: https://drive.google.com/drive/u/2/folders/0B9tUHkbrCEPMMmFha0hmRFZiZGs

Requirements:
- [ ] Digitize the map
- [ ] Should be able to zoom in and out of different parts of the map
- [ ] Station numbers are represented as pins

**Comment by hiimben** [comment]
The map might not be the landing screen - it would make more sense for users to see WHICH station they're going to first, then check where it is/how to get there. I'll keep working on the design, but I think the landing screen is likely going to be the schedule!
