### ISSUE TITLE
When an alert is sent out, send an SMS to educators

### ISSUE THREAD

**Issue by theRoughCode** [uwblueprint/water-festival#66]
This should be done after #65.

After an alert has been sent, all educators should be sent an SMS using the [Twilio SMS API](https://www.twilio.com/sms).

*Note*:  Only educators who've expressed that they'll be present on that day should be notified.

**Comment by AbhiPrasad** [comment]
Closed with https://github.com/uwblueprint/water-festival-backend/pull/16
